{
  "pipe_parallel_size": 0,
  "model_parallel_size": 1,
  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,
  "rope_fusion": false,
  "layernorm_fusion": false,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.0e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 3.0e-5,
  "lr_decay_style": "cosine",

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },

  "data_impl": "mmap",
  "split": "949,50,1",

  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0.0,
  "attention_dropout": 0.0,

  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "bf16"
  },
  "distributed_backend": "nccl",
  "train_micro_batch_size_per_gpu": 16,
  "gradient_accumulation_steps": 1,

  "train_iters": 5000,
  "lr_decay_iters": 10000,
  "warmup": 0.01,
  "checkpoint_factor": 1000,
  "eval_interval": 500,
  "eval_iters": 10,
  "log_interval": 10,
  "steps_per_print": 10,
  "keep_last_n_checkpoints": 10,
  "wall_clock_breakdown": true,
  "checkpoint_validation_with_forward_pass": false
}